defmodule PhoneyApi.Repo.Migrations.AddConstraitToUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify(:password, :text, null: false)
      modify(:username, :text, null: false)
      modify(:email, :text, null: false)
      add(:role, :text)
    end

    create unique_index(:users, [:email], name: "users_email_index")
  end

  def down do
    drop_if_exists(unique_index(:users, [:email], name: "users_email_index"))

    alter table(:users) do
      remove(:role)
      modify(:email, :text, null: true)
      modify(:username, :text, null: true)
      modify(:password, :text, null: true)
    end
  end
end
