defmodule PhoneyApi.Repo.Migrations.AddEmbedToContact do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Remove address column first
    alter table(:contacts) do
      remove(:address)
    end

    alter table(:contacts) do
      add(:address, :map)
    end
  end

  def down do
    alter table(:contacts) do
      modify(:address, :text)
    end
  end
end
